### ISSUE TITLE
conditional margin to ul menu and h1 archive title

### ISSUE THREAD

**Issue by aryanrajseo** [seothemes/genesis-customizer-plugin#8]
1. Add margin 0 for menu ul. Global ul class adding margin 1.6rem at bottom for menu ul add space in bottom. It should be fit to center without any space margin or padding.

2. Add margin 0 for archive title. The archive title box h1 have margin bottom not look good.

**Comment by seothemes** [comment]
I came across these issues too. Thanks for reporting.
